#ifndef SETTINGS_H
#define SETTINGS_H

#define PRINT_INV_DISTORT_COEFF false
#define SUBTRACT_OFFSET false

#define SYNC_LENGTH 1000
#define ZOOM_RATIO  0.5
#define PREFETCH_LENGTH 200
#define MIP_ANGLE_THRES 0.05
#endif // SETTINGS_H

